export type PlaceCategory =
  | "home"
  | "class"
  | "food"
  | "study"
  | "transit"
  | "shopping"
  | "service"
  | "attraction"
  | "landmark";

export type PlaceArea =
  | "west"
  | "east"
  | "ninth"
  | "essentials"
  | "durham"
  | "triangle"
  | "travel";

export type PlaceSource = {
  label: string;
  url: string;
  checkedAt: string;
};

export type Place = {
  id: string;
  name: string;
  shortName: string;
  category: PlaceCategory;
  categoryLabel: string;
  area?: PlaceArea;
  coordinates: [number, number];
  room?: string;
  address?: string;
  summary: string;
  facts: string[];
  source: PlaceSource;
  confidence: "verified" | "cross-checked" | "review";
  markerLabel: string;
  previewEmoji?: string;
  shuttle?: {
    route: string;
    summary: string;
    liveUrl: string;
  };
  links?: Array<{ label: string; url: string }>;
};

export type ShuttleStop = {
  id: string;
  name: string;
  shortName: string;
  area: PlaceArea;
  coordinates: [number, number];
  stopCode?: string;
};

export const SHUTTLE_ROUTE_NAME = "CSF?C1?Swift Avenue Shuttle";

export const SHUTTLE_STOPS: ShuttleStop[] = [
  {
    id: "east-campus-statue-stop",
    name: "East Campus Statue",
    shortName: "East Campus Statue",
    area: "east",
    coordinates: [36.0052024856, -78.9147518322],
  },
  {
    id: "blue-light-shuttle-stop",
    name: "The Blue Light Living",
    shortName: "Blue Light Stop",
    area: "east",
    coordinates: [36.005898, -78.92179],
  },
  {
    id: "swift-300-shuttle-stop",
    name: "Swift Ave at 300 Swift",
    shortName: "300 Swift Stop",
    area: "east",
    coordinates: [36.0027490109, -78.9215145362],
  },
  {
    id: "swift-campus-west-stop",
    name: "Swift at Campus Drive",
    shortName: "Swift / Campus W",
    area: "east",
    coordinates: [36.00012, -78.923389],
  },
  {
    id: "nasher-westbound-stop",
    name: "Campus Dr at Nasher Westbound",
    shortName: "Nasher Westbound",
    area: "west",
    coordinates: [36.000204, -78.926926],
  },
  {
    id: "anderson-westbound-stop",
    name: "Campus Dr at Anderson",
    shortName: "Anderson Westbound",
    area: "west",
    coordinates: [36.000055, -78.93004],
  },
  {
    id: "admissions-westbound-stop",
    name: "Campus Dr at Admissions Westbound",
    shortName: "Admissions Westbound",
    area: "west",
    coordinates: [35.999146, -78.933243],
  },
  {
    id: "west-campus-chapel-stop",
    name: "West Campus Chapel",
    shortName: "West Chapel Stop",
    area: "west",
    coordinates: [36.000953, -78.938252],
    stopCode: "12018",
  },
  {
    id: "chapel-circle-eastbound-stop",
    name: "Campus Dr at Chapel Circle Eastbound",
    shortName: "Chapel Circle E",
    area: "west",
    coordinates: [35.999056, -78.933058],
    stopCode: "12015",
  },
  {
    id: "anderson-eastbound-stop",
    name: "Campus Dr at Anderson St Eastbound",
    shortName: "Anderson Eastbound",
    area: "west",
    coordinates: [36.000025, -78.930371],
    stopCode: "12012",
  },
  {
    id: "nasher-eastbound-stop",
    name: "Campus Dr at Nasher Eastbound",
    shortName: "Nasher Eastbound",
    area: "west",
    coordinates: [35.999812, -78.928486],
  },
  {
    id: "swift-campus-eastbound-stop",
    name: "Campus Dr at Swift Ave Eastbound",
    shortName: "Swift / Campus E",
    area: "east",
    coordinates: [35.999964, -78.923602],
  },
  {
    id: "swift-caswell-eastbound-stop",
    name: "Swift Avenue at Caswell Pl Eastbound",
    shortName: "Swift / Caswell",
    area: "east",
    coordinates: [36.002669, -78.921374],
  },
];

// Duke Transit GTFS route shape, simplified from 473 to 68 points for the map.
export const SHUTTLE_ROUTE_SHAPE: [number, number][] = [
  [36.00518, -78.91476],
  [36.00343, -78.91479],
  [36.00557, -78.91895],
  [36.00598, -78.91983],
  [36.00639, -78.92128],
  [36.00654, -78.922],
  [36.00655, -78.92227],
  [36.0063, -78.92229],
  [36.00606, -78.92239],
  [36.00578, -78.92108],
  [36.00538, -78.91989],
  [36.00509, -78.91993],
  [36.00473, -78.92007],
  [36.00347, -78.9209],
  [35.99999, -78.92341],
  [36.00036, -78.92521],
  [36.00039, -78.92557],
  [36.00032, -78.92633],
  [35.99998, -78.92756],
  [35.99987, -78.92834],
  [35.99988, -78.92893],
  [36.00007, -78.93049],
  [36.00006, -78.93088],
  [36.00001, -78.93113],
  [35.99986, -78.9315],
  [35.99919, -78.93281],
  [35.99908, -78.93322],
  [35.99901, -78.93386],
  [35.99912, -78.93393],
  [35.99916, -78.93402],
  [35.99916, -78.93414],
  [35.99908, -78.93426],
  [36.0003, -78.93689],
  [36.00062, -78.93754],
  [36.0008, -78.93752],
  [36.00106, -78.93805],
  [36.00091, -78.93824],
  [36.00073, -78.93825],
  [36.00052, -78.93776],
  [36.00054, -78.93764],
  [36.00062, -78.93754],
  [35.99908, -78.93426],
  [35.99902, -78.93429],
  [35.99891, -78.93427],
  [35.99882, -78.9341],
  [35.99885, -78.93396],
  [35.99893, -78.93388],
  [35.99901, -78.93386],
  [35.99905, -78.93341],
  [35.99919, -78.93281],
  [35.99986, -78.9315],
  [36.00001, -78.93113],
  [36.00006, -78.93088],
  [36.00007, -78.93049],
  [35.99988, -78.92893],
  [35.99987, -78.92834],
  [35.99998, -78.92756],
  [36.00032, -78.92633],
  [36.00039, -78.92557],
  [36.00036, -78.92521],
  [35.99999, -78.92341],
  [36.00347, -78.9209],
  [36.00473, -78.92007],
  [36.00509, -78.91993],
  [36.00598, -78.91983],
  [36.00557, -78.91895],
  [36.00343, -78.91479],
  [36.00518, -78.91476],
];

export const CATEGORY_META: Record<
  PlaceCategory,
  { label: string; color: string; soft: string }
> = {
  home: { label: "??", color: "#d83b3e", soft: "#fff0ef" },
  class: { label: "??", color: "#6755d9", soft: "#f1efff" },
  food: { label: "??", color: "#c36b14", soft: "#fff4e6" },
  study: { label: "??", color: "#1769aa", soft: "#eaf4ff" },
  transit: { label: "??", color: "#007a5e", soft: "#e7f7f2" },
  shopping: { label: "??", color: "#a14d87", soft: "#fbeefa" },
  service: { label: "??", color: "#516170", soft: "#edf1f4" },
  attraction: { label: "??", color: "#2f7d32", soft: "#eaf7e9" },
  landmark: { label: "??", color: "#0f7b6c", soft: "#e8f7f2" },
};

export const AREA_META: Record<
  PlaceArea,
  { label: string; shortLabel: string; description: string }
> = {
  west: {
    label: "Duke West Campus",
    shortLabel: "West",
    description: "????????????",
  },
  east: {
    label: "East Campus + Swift",
    shortLabel: "East",
    description: "??????East?West ??? Swift",
  },
  ninth: {
    label: "Ninth Street",
    shortLabel: "9th St",
    description: "?????????????",
  },
  essentials: {
    label: "????",
    shortLabel: "??",
    description: "??????????????",
  },
  durham: {
    label: "Durham ??",
    shortLabel: "Durham",
    description: "?????????????",
  },
  triangle: {
    label: "Triangle ??",
    shortLabel: "??",
    description: "Chapel Hill?Raleigh ? Cary",
  },
  travel: {
    label: "?????",
    shortLabel: "??",
    description: "RDU ????????",
  },
};

export const AREA_ORDER: PlaceArea[] = [
  "west",
  "east",
  "ninth",
  "essentials",
  "durham",
  "triangle",
  "travel",
];

const BASE_PLACES: Place[] = [
  {
    id: "edens-1a",
    name: "Edens Quad 1A",
    shortName: "Edens 1A",
    category: "home",
    categoryLabel: "?? ? ????",
    coordinates: [35.99847, -78.93678],
    address: "419 Towerview Drive",
    summary: "????????????? Duke ??????????????",
    facts: [
      "????1 ??24 ????",
      "???/???????1 ? 102T?103T",
      "?????419 Towerview Drive",
      "?????? 1A ????????????????",
    ],
    source: {
      label: "Duke Campus Mail + OSM building",
      url: "https://postoffice.duke.edu/addressing-mail/dormitory-street-addresses/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "1A",
    links: [
      {
        label: "???????",
        url: "https://www.dukestores.duke.edu/index.php/laundry/",
      },
      {
        label: "Edens ???",
        url: "https://students.duke.edu/living/housing/upperclass-housing/upperclass-floor-plans/",
      },
    ],
  },
  {
    id: "physics",
    name: "Physics Building",
    shortName: "Physics",
    category: "class",
    categoryLabel: "???",
    coordinates: [36.003137, -78.942266],
    room: "235",
    address: "120 Science Drive",
    summary: "MATH 333 ??? MATH 431 ?? Physics 235???????????",
    facts: [
      "MATH 333 ? Complex Analysis",
      "MATH 431 ? Real Analysis????",
      "???? Physics Building ????? ePrint ??",
    ],
    source: {
      label: "Duke ePrint ? Physics Lobby",
      url: "https://eprint.oit.duke.edu/printers/1081",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "P",
  },
  {
    id: "social-sciences",
    name: "Social Sciences Building",
    shortName: "Social Sciences",
    category: "class",
    categoryLabel: "?????",
    coordinates: [36.001843, -78.937277],
    room: "136",
    address: "419 Chapel Drive",
    summary: "GLHLTH 101 ???????????????????",
    facts: [
      "GLHLTH 101",
      "????? 10:05?11:20",
      "???Social Sciences 136",
    ],
    source: {
      label: "Duke ePrint ? SocSci 211",
      url: "https://eprint.oit.duke.edu/printers/73",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "S",
  },
  {
    id: "french-science",
    name: "French Family Science Center",
    shortName: "French Science",
    category: "class",
    categoryLabel: "???",
    coordinates: [36.002862, -78.943388],
    room: "2231",
    summary: "Financial Accounting 174 ???????? section ?????? DukeHub ??????",
    facts: [
      "Financial Accounting 174",
      "????? 8:30?9:45",
      "???French Science 2231",
      "?????????????? 1?3 ?",
    ],
    source: {
      label: "Duke ePrint ? FFSC Lower Level",
      url: "https://eprint.oit.duke.edu/printers/1066",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "F",
  },
  {
    id: "languages",
    name: "Languages Building",
    shortName: "Languages",
    category: "class",
    categoryLabel: "???",
    coordinates: [36.002133, -78.938161],
    summary: "KOREAN 101 ???????? section???????? DukeHub ?????",
    facts: [
      "KOREAN 101",
      "??????????? 11:45?13:00",
      "?????? Romance Languages ??????",
    ],
    source: {
      label: "Duke ePrint ? Romance Languages",
      url: "https://eprint.oit.duke.edu/printers/158",
      checkedAt: "2026-07-23",
    },
    confidence: "review",
    markerLabel: "L",
  },
  {
    id: "bryan-center",
    name: "Bryan Center",
    shortName: "Bryan Center",
    category: "food",
    categoryLabel: "?????",
    coordinates: [36.001139, -78.941588],
    address: "125 Science Drive",
    summary: "2026 ??????????????? Panda?Twinnie's ? Starbucks ?????? Bryan ???",
    facts: [
      "Beyu Blue Coffee ? Bryan ??Duke Store ????",
      "McDonald's ? 2 ?",
      "Gothic Grill ? 2 ?",
      "It's Thyme ? Plaza Level",
      "ePrint?Lower Level?ATM/Vending Room ?????",
    ],
    source: {
      label: "Duke ePrint ? Bryan Lower Level",
      url: "https://eprint.oit.duke.edu/printers/142",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "B",
    links: [
      {
        label: "?????????",
        url: "https://students.duke.edu/living/dining/dining-locations/",
      },
    ],
  },
  {
    id: "brodhead",
    name: "Brodhead Center",
    shortName: "Brodhead",
    category: "food",
    categoryLabel: "?????",
    coordinates: [36.000728, -78.939136],
    summary: "? West Union????????????? Bryan Center ????",
    facts: [
      "???????????",
      "Ground Floor 058T ???????",
      "2 ? Vending Room ? ePrint",
      "???????? Duke Dining ??????",
    ],
    source: {
      label: "Duke ePrint ? Brodhead Center",
      url: "https://eprint.oit.duke.edu/printers/899",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "D",
    links: [
      {
        label: "?????????",
        url: "https://students.duke.edu/living/dining/dining-locations/",
      },
    ],
  },
  {
    id: "perkins",
    name: "Perkins Library",
    shortName: "Perkins",
    category: "study",
    categoryLabel: "?????",
    coordinates: [36.003264, -78.938178],
    summary: "?????????????? Bostock ???",
    facts: [
      "1 ? Lobby / Breezeway ??? ePrint",
      "??? The Link ? OIT ???",
      "??????????",
    ],
    source: {
      label: "Duke ePrint ? Perkins Lobby",
      url: "https://eprint.oit.duke.edu/printers/186",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "K",
    links: [
      {
        label: "Duke Libraries",
        url: "https://library.duke.edu/",
      },
    ],
  },
  {
    id: "bostock",
    name: "Bostock Library",
    shortName: "Bostock",
    category: "study",
    categoryLabel: "????",
    coordinates: [36.002903, -78.938339],
    summary: "?? Perkins?????????????",
    facts: [
      "The Edge ?????? ePrint",
      "? Perkins ????",
      "???? The Edge ??????",
    ],
    source: {
      label: "Duke ePrint ? Bostock Edge",
      url: "https://eprint.oit.duke.edu/printers/172",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "O",
  },
  {
    id: "duke-chapel",
    name: "Duke Chapel",
    shortName: "Chapel",
    category: "landmark",
    categoryLabel: "????",
    coordinates: [36.0018682, -78.9402861],
    summary: "West Campus ??????????",
    facts: [
      "? Chapel ????? Bryan Center",
      "????? Brodhead ? Social Sciences",
      "?????? OpenStreetMap ??? Duke ?????",
    ],
    source: {
      label: "Duke Campus Map + OpenStreetMap",
      url: "https://maps.duke.edu/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "C",
  },
  {
    id: "few-quad",
    name: "Few Quad",
    shortName: "Few Quad",
    category: "home",
    categoryLabel: "West ??",
    area: "west",
    coordinates: [36.000083, -78.938523],
    summary: "?? West Campus ????? Chapel?Brodhead ??????",
    facts: ["? 430 ??????", "????????????? ePrint"],
    source: {
      label: "Duke Student Affairs ? Few Quad",
      url: "https://students.duke.edu/quadex/few-quad/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "FQ",
    previewEmoji: "??",
  },
  {
    id: "keohane-quad",
    name: "Keohane Quad",
    shortName: "Keohane",
    category: "home",
    categoryLabel: "West ??",
    area: "west",
    coordinates: [35.99895, -78.9376],
    summary: "?? Edens?Wannamaker ? Towerview Drive ? West Campus ????",
    facts: ["?? Keohane 4A?4B?4D?4E", "? Edens ????"],
    source: {
      label: "Duke Housing ? Upperclass Floor Plans",
      url: "https://students.duke.edu/living/housing/upperclass-housing/upperclass-floor-plans/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "KQ",
    previewEmoji: "??",
  },
  {
    id: "wannamaker-quad",
    name: "Wannamaker Quad",
    shortName: "Wannamaker",
    category: "home",
    categoryLabel: "West ??",
    area: "west",
    coordinates: [35.99866, -78.93913],
    summary: "West Campus ???????? Towerview Road ????????",
    facts: ["?? Wannamaker 1?4", "Duke Dining ???????????"],
    source: {
      label: "Duke Housing ? Upperclass Floor Plans",
      url: "https://students.duke.edu/living/housing/upperclass-housing/upperclass-floor-plans/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "WQ",
    previewEmoji: "??",
  },
  {
    id: "east-bus-stop",
    name: "East Campus Statue Shuttle Stop",
    shortName: "East Campus Stop",
    category: "transit",
    categoryLabel: "C1 / CSF ???",
    area: "east",
    coordinates: [36.0052024856, -78.9147518322],
    summary: "?? CSF/C1?Swift ? East Campus ??????????? East Campus Statue?",
    facts: ["???????? Duke GTFS", "? TransLoc ???? Quad ???????"],
    source: {
      label: "Duke Transit ? CSF East?Swift?West",
      url: "https://parking.duke.edu/buses-vans/csf-east-swift-avenue-west/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "C1",
    previewEmoji: "??",
    shuttle: {
      route: "C1 / CSF",
      summary: "East Campus Quad ? Swift Avenue ? West Campus Chapel",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "east-marketplace",
    name: "East Union Marketplace",
    shortName: "Marketplace",
    category: "food",
    categoryLabel: "East ???",
    area: "east",
    coordinates: [36.0069, -78.91475],
    summary: "East Campus ????????????????????????????",
    facts: ["?? East Union", "???????? Duke Dining ??????"],
    source: {
      label: "Duke Dining ? Marketplace",
      url: "https://students.duke.edu/living/dining/dining-locations/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "MP",
    previewEmoji: "???",
    shuttle: {
      route: "C1 / CSF",
      summary: "West Campus Chapel ? East Campus Quad??????",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "lilly-library",
    name: "Lilly Library",
    shortName: "Lilly Library",
    category: "study",
    categoryLabel: "East ??",
    area: "east",
    coordinates: [36.0076033, -78.9153485],
    summary: "East Campus ????????????????????",
    facts: ["?????????", "?? East Campus ????"],
    source: {
      label: "Duke Libraries ? Lilly Library",
      url: "https://library.duke.edu/lilly",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "LL",
    previewEmoji: "??",
    shuttle: {
      route: "C1 / CSF",
      summary: "West Campus Chapel ? East Campus Quad??????",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "baldwin-auditorium",
    name: "Baldwin Auditorium",
    shortName: "Baldwin",
    category: "landmark",
    categoryLabel: "?????",
    area: "east",
    coordinates: [36.0090551, -78.9146329],
    summary: "East Campus ?????????????????????",
    facts: ["?? East Campus ?????", "????? Duke Arts ??"],
    source: {
      label: "Duke Arts ? Venues",
      url: "https://arts.duke.edu/venues/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "BA",
    previewEmoji: "??",
    shuttle: {
      route: "C1 / CSF",
      summary: "West Campus Chapel ? East Campus Quad??????",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "brodie-recreation",
    name: "Brodie Recreation Center",
    shortName: "Brodie Gym",
    category: "landmark",
    categoryLabel: "????",
    area: "east",
    coordinates: [36.0076447, -78.9170402],
    summary: "East Campus ???????????",
    facts: ["??????????????", "?? DukeCard"],
    source: {
      label: "Duke Recreation & Physical Education",
      url: "https://recreation.duke.edu/facilities/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "BR",
    previewEmoji: "???",
    shuttle: {
      route: "C1 / CSF",
      summary: "West Campus Chapel ? East Campus Quad??????",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "alspaugh-hall",
    name: "Alspaugh Residence Hall",
    shortName: "Alspaugh",
    category: "home",
    categoryLabel: "East ??",
    area: "east",
    coordinates: [36.0081507, -78.9152177],
    summary: "East Campus ???????? Baldwin Auditorium ? Lilly Library?",
    facts: ["? 120 ??????", "East Campus 14 ????????"],
    source: {
      label: "Duke Housing ? East Campus Houses",
      url: "https://students.duke.edu/living/housing/first-year-housing/east-campus-houses/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "AL",
    previewEmoji: "???",
    shuttle: {
      route: "C1 / CSF",
      summary: "West Campus Chapel ? East Campus Quad??????",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "blackwell-hall",
    name: "Blackwell Residence Hall",
    shortName: "Blackwell",
    category: "home",
    categoryLabel: "East ??",
    area: "east",
    coordinates: [36.0064482, -78.9164539],
    summary: "East Campus ???????? Brodie Recreation Center?",
    facts: ["??????", "?????????? HRL ??"],
    source: {
      label: "Duke Housing ? East Campus Houses",
      url: "https://students.duke.edu/living/housing/first-year-housing/east-campus-houses/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "BL",
    previewEmoji: "???",
    shuttle: {
      route: "C1 / CSF",
      summary: "West Campus Chapel ? East Campus Quad??????",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "southgate-hall",
    name: "Southgate Residence Hall",
    shortName: "Southgate",
    category: "home",
    categoryLabel: "East ??",
    area: "east",
    coordinates: [36.0060314, -78.9179317],
    summary: "East Campus ???????????? Swift ? Main Street ???",
    facts: ["??????", "1921 ???"],
    source: {
      label: "Duke Housing ? East Campus Houses",
      url: "https://students.duke.edu/living/housing/first-year-housing/east-campus-houses/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "SG",
    previewEmoji: "???",
    shuttle: {
      route: "C1 / CSF",
      summary: "West Campus Chapel ? East Campus Quad??????",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "trinity-hall",
    name: "Trinity Residence Hall",
    shortName: "Trinity",
    category: "home",
    categoryLabel: "East ??",
    area: "east",
    coordinates: [36.0065411, -78.9186292],
    summary: "East Campus ?????????? Southgate ? Main Street?",
    facts: ["??????", "?? East Campus ????"],
    source: {
      label: "Duke Housing ? East Campus Houses",
      url: "https://students.duke.edu/living/housing/first-year-housing/east-campus-houses/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "TR",
    previewEmoji: "???",
    shuttle: {
      route: "C1 / CSF",
      summary: "West Campus Chapel ? East Campus Quad??????",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "swift-300",
    name: "300 Swift Avenue",
    shortName: "300 Swift",
    category: "transit",
    categoryLabel: "SWS / CSF ???",
    area: "east",
    coordinates: [36.0027490109, -78.9215145362],
    summary: "Swift Avenue ??????????? East?Swift ? West Campus?",
    facts: ["CSF ?? ID 13009", "????? Swift Avenue Shuttle"],
    source: {
      label: "Duke Transit ? CSF East?Swift?West",
      url: "https://parking.duke.edu/buses-vans/csf-east-swift-avenue-west/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "SW",
    previewEmoji: "??",
    shuttle: {
      route: "SWS / CSF",
      summary: "East Campus ? 300 Swift ? West Campus",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "blue-light-living",
    name: "The Blue Light Living",
    shortName: "Blue Light",
    category: "home",
    categoryLabel: "??????",
    area: "east",
    coordinates: [36.005522, -78.9226205],
    address: "1605 Erwin Road",
    summary: "Duke ???????CSF ??? East?West ?????",
    facts: ["CSF ?? ID 12131", "?????????? TransLoc"],
    source: {
      label: "Duke Transit ? CSF East?Swift?West",
      url: "https://parking.duke.edu/buses-vans/csf-east-swift-avenue-west/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "BL",
    previewEmoji: "??",
    shuttle: {
      route: "CSF",
      summary: "East Campus ? Blue Light ? Swift ? West Campus",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "elmos-diner",
    name: "Elmo's Diner",
    shortName: "Elmo's Diner",
    category: "food",
    categoryLabel: "???? ? Diner",
    area: "ninth",
    coordinates: [36.0104063, -78.9216996],
    address: "776 9th Street",
    summary: "Ninth Street ???????????????????? diner ???",
    facts: ["????????", "? East Campus ????"],
    source: {
      label: "Discover Durham ? Ninth Street Guide",
      url: "https://www.discoverdurham.com/district-guides/the-ultimate-guide-to-ninth-street-duke-university/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "ED",
    previewEmoji: "??",
  },
  {
    id: "monuts",
    name: "Monuts",
    shortName: "Monuts",
    category: "food",
    categoryLabel: "?? ? ???",
    area: "ninth",
    coordinates: [36.0139103, -78.9215285],
    address: "1002 9th Street",
    summary: "???????????????? Ninth Street ???",
    facts: ["?????????", "????????????????"],
    source: {
      label: "Discover Durham ? Ninth Street Guide",
      url: "https://www.discoverdurham.com/directory/monuts/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "MO",
    previewEmoji: "??",
  },
  {
    id: "cosmic-cantina",
    name: "Cosmic Cantina",
    shortName: "Cosmic Cantina",
    category: "food",
    categoryLabel: "??? ? ??",
    area: "ninth",
    coordinates: [36.0077961, -78.9218492],
    address: "1920 Perry Street",
    summary: "Ninth Street ???????????? burrito ? quesadilla ???",
    facts: ["??????????", "?????????"],
    source: {
      label: "Discover Durham ? Duke Hotspots",
      url: "https://www.discoverdurham.com/blog/best-hotspots-duke-university/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "CC",
    previewEmoji: "??",
  },
  {
    id: "lime-lemon",
    name: "Lime & Lemon Indian Grill",
    shortName: "Lime & Lemon",
    category: "food",
    categoryLabel: "???",
    area: "ninth",
    coordinates: [36.0113, -78.92162],
    address: "811 9th Street",
    summary: "?????????????????",
    facts: ["?? Ninth Street ??", "??????????????"],
    source: {
      label: "Discover Durham ? Ninth Street Guide",
      url: "https://www.discoverdurham.com/district-guides/the-ultimate-guide-to-ninth-street-duke-university/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "L&L",
    previewEmoji: "??",
  },
  {
    id: "dains-place",
    name: "Dain's Place",
    shortName: "Dain's Place",
    category: "food",
    categoryLabel: "?? ? Bar",
    area: "ninth",
    coordinates: [36.0095674, -78.9217353],
    address: "754 9th Street",
    summary: "Ninth Street ????????????????",
    facts: ["??????", "???????????"],
    source: {
      label: "Discover Durham ? Ninth Street Guide",
      url: "https://www.discoverdurham.com/district-guides/the-ultimate-guide-to-ninth-street-duke-university/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "DP",
    previewEmoji: "??",
  },
  {
    id: "banhs-cuisine",
    name: "Banh's Cuisine",
    shortName: "Banh's Cuisine",
    category: "food",
    categoryLabel: "?? ? ??",
    area: "ninth",
    coordinates: [36.0094817, -78.9218716],
    address: "752 9th Street",
    summary: "?????????????????????????",
    facts: ["??????????", "?????????????"],
    source: {
      label: "Discover Durham ? Ninth Street Guide",
      url: "https://www.discoverdurham.com/district-guides/the-ultimate-guide-to-ninth-street-duke-university/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "BH",
    previewEmoji: "??",
  },
  {
    id: "vin-rouge",
    name: "Vin Rouge",
    shortName: "Vin Rouge",
    category: "food",
    categoryLabel: "??",
    area: "ninth",
    coordinates: [36.0106219, -78.9223235],
    address: "2010 Hillsborough Road",
    summary: "Ninth Street ???????????????????",
    facts: ["??????", "????????????"],
    source: {
      label: "Discover Durham ? Ninth Street Guide",
      url: "https://www.discoverdurham.com/directory/vin-rouge/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "VR",
    previewEmoji: "????",
  },
  {
    id: "juju-durham",
    name: "Juju Durham",
    shortName: "Juju",
    category: "food",
    categoryLabel: "???? ? Tapas",
    area: "ninth",
    coordinates: [36.0096915, -78.9223473],
    address: "737 9th Street",
    summary: "???????????????????",
    facts: ["??????", "????????"],
    source: {
      label: "Discover Durham ? Ninth Street Guide",
      url: "https://www.discoverdurham.com/district-guides/the-ultimate-guide-to-ninth-street-duke-university/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "JU",
    previewEmoji: "??",
  },
  {
    id: "cloche-coffee",
    name: "Cloche Coffee",
    shortName: "Cloche Coffee",
    category: "food",
    categoryLabel: "?? ? ??",
    area: "ninth",
    coordinates: [36.0077, -78.92295],
    address: "721 Broad Street",
    summary: "East Campus ?????????????????????",
    facts: ["??????", "? East Campus ????"],
    source: {
      label: "Discover Durham ? Ninth Street Guide",
      url: "https://www.discoverdurham.com/district-guides/the-ultimate-guide-to-ninth-street-duke-university/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "CL",
    previewEmoji: "?",
  },
  {
    id: "cocoa-cinnamon",
    name: "Cocoa Cinnamon ? Old West Durham",
    shortName: "Cocoa Cinnamon",
    category: "food",
    categoryLabel: "?? ? ???",
    area: "ninth",
    coordinates: [36.0115807, -78.9301586],
    address: "2627 Hillsborough Road",
    summary: "Old West Durham ??????????? Ninth Street ???????",
    facts: ["? Ninth Street ?????", "?????????"],
    source: {
      label: "Discover Durham ? Ninth Street Guide",
      url: "https://www.discoverdurham.com/district-guides/the-ultimate-guide-to-ninth-street-duke-university/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "CO",
    previewEmoji: "?",
  },
  {
    id: "whole-foods-durham",
    name: "Whole Foods Market ? Durham",
    shortName: "Whole Foods",
    category: "shopping",
    categoryLabel: "????",
    area: "essentials",
    coordinates: [36.0070992, -78.9205563],
    address: "621 Broad Street",
    summary: "? East Campus ? Ninth Street ????????????",
    facts: ["???????????", "???????????"],
    source: {
      label: "Whole Foods ? Durham Store",
      url: "https://www.wholefoodsmarket.com/stores/durham",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "WF",
    previewEmoji: "??",
  },
  {
    id: "harris-teeter-ninth",
    name: "Harris Teeter ? Ninth Street",
    shortName: "Harris Teeter",
    category: "shopping",
    categoryLabel: "???? ? ??",
    area: "essentials",
    coordinates: [36.009799, -78.9241832],
    address: "2107 Hillsborough Road",
    summary: "Ninth Street ??????????????",
    facts: ["?????????", "???????????"],
    source: {
      label: "Harris Teeter ? Durham Store",
      url: "https://www.harristeeter.com/stores/pharmacy/nc/durham/097/00394",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "HT",
    previewEmoji: "??",
  },
  {
    id: "food-lion-west-main",
    name: "Food Lion ? West Main",
    shortName: "Food Lion",
    category: "shopping",
    categoryLabel: "????",
    area: "essentials",
    coordinates: [36.0142132, -78.9340045],
    address: "2930 West Main Street",
    summary: "Old West Durham ??????????????",
    facts: ["? West Campus ??", "???????"],
    source: {
      label: "North Carolina Authorized Retailer List",
      url: "https://www.ncdhhs.gov/north-carolina-authorized-wic-vendors/open",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "FL",
    previewEmoji: "??",
  },
  {
    id: "durham-coop",
    name: "Durham Co-op Market",
    shortName: "Durham Co-op",
    category: "shopping",
    categoryLabel: "???????",
    area: "essentials",
    coordinates: [35.9965133, -78.9167043],
    address: "1111 West Chapel Hill Street",
    summary: "????????????????????????",
    facts: ["?? Burch Avenue", "???????"],
    source: {
      label: "Durham Co-op Market",
      url: "https://durham.coop/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "DC",
    previewEmoji: "??",
  },
  {
    id: "li-mings",
    name: "Li Ming's Global Mart",
    shortName: "Li Ming's",
    category: "shopping",
    categoryLabel: "??????",
    area: "essentials",
    coordinates: [35.9662353, -78.9629676],
    address: "3400 Westgate Drive",
    summary: "????????????????????????????",
    facts: ["??????????", "?? South Square ??????"],
    source: {
      label: "OpenStreetMap + Store Listing",
      url: "https://www.openstreetmap.org/?mlat=35.9662353&mlon=-78.9629676#map=18/35.9662353/-78.9629676",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "LM",
    previewEmoji: "??",
  },
  {
    id: "costco-durham",
    name: "Costco Wholesale ? Durham",
    shortName: "Costco",
    category: "shopping",
    categoryLabel: "????",
    area: "essentials",
    coordinates: [36.0290976, -78.9138789],
    address: "1510 North Pointe Drive",
    summary: "??????????????????",
    facts: ["??????", "???????????"],
    source: {
      label: "Costco Warehouse Locator",
      url: "https://www.costco.com/warehouse-locations/durham-nc-249.html",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "CT",
    previewEmoji: "??",
  },
  {
    id: "target-south-square",
    name: "Target ? South Square",
    shortName: "Target",
    category: "shopping",
    categoryLabel: "????",
    area: "essentials",
    coordinates: [35.965602, -78.960766],
    address: "4037 Durham-Chapel Hill Boulevard",
    summary: "?????????????????????",
    facts: ["? Li Ming's ????", "????"],
    source: {
      label: "Target Store Locator",
      url: "https://www.target.com/store-locator/find-stores/27707",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "TG",
    previewEmoji: "??",
  },
  {
    id: "walmart-new-hope",
    name: "Walmart ? New Hope Commons",
    shortName: "Walmart",
    category: "shopping",
    categoryLabel: "????",
    area: "essentials",
    coordinates: [35.9550347, -78.9990623],
    address: "5450 New Hope Commons Drive",
    summary: "??????????????????????",
    facts: ["??????????", "?? New Hope Commons ??????"],
    source: {
      label: "Walmart Store Finder",
      url: "https://www.walmart.com/store/3182-durham-nc",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "WM",
    previewEmoji: "??",
  },
  {
    id: "duke-credit-union",
    name: "Duke University Credit Union",
    shortName: "Duke Credit Union",
    category: "service",
    categoryLabel: "?? ? ?????",
    area: "essentials",
    coordinates: [36.0075572, -78.9262548],
    address: "2200 West Main Street, Suite L100",
    summary: "??????? Duke ?????????????????",
    facts: ["??????????????", "?????919-684-6704"],
    source: {
      label: "Duke University Credit Union",
      url: "https://www.dukefcu.org/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "CU",
    previewEmoji: "??",
  },
  {
    id: "rdu-terminal-2",
    name: "RDU Airport ? Terminal 2",
    shortName: "RDU Terminal 2",
    category: "transit",
    categoryLabel: "?? ? ?????",
    area: "travel",
    coordinates: [35.8782578, -78.7924525],
    address: "2400 John Brantley Boulevard",
    summary: "RDU ???????????????????",
    facts: ["????????????????????", "???????????"],
    source: {
      label: "RDU ? Ground Transportation",
      url: "https://www.rdu.com/ground-transportation/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "T2",
    previewEmoji: "??",
    links: [
      {
        label: "RDU ???????",
        url: "https://www.rdu.com/ground-transportation/bus-and-rail-service/",
      },
    ],
  },
  {
    id: "rdu-terminal-1",
    name: "RDU Airport ? Terminal 1",
    shortName: "RDU Terminal 1",
    category: "transit",
    categoryLabel: "?????",
    area: "travel",
    coordinates: [35.8785, -78.7872],
    summary: "RDU Terminal 1???????????????",
    facts: ["GoTriangle ??????? Terminal 2 ??", "?????? Zone ??"],
    source: {
      label: "RDU ? Bus and Rail Service",
      url: "https://www.rdu.com/ground-transportation/bus-and-rail-service/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "T1",
    previewEmoji: "??",
  },
  {
    id: "duke-gardens",
    name: "Sarah P. Duke Gardens",
    shortName: "Duke Gardens",
    category: "attraction",
    categoryLabel: "?? ? ??",
    area: "durham",
    coordinates: [36.0024247, -78.9328121],
    summary: "55 ??????????????????????",
    facts: ["??????????????", "? West Campus ???"],
    source: {
      label: "Discover Durham ? Things to Do",
      url: "https://www.discoverdurham.com/things-to-do/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "DG",
    previewEmoji: "??",
  },
  {
    id: "nasher-museum",
    name: "Nasher Museum of Art",
    shortName: "Nasher Museum",
    category: "attraction",
    categoryLabel: "?????",
    area: "durham",
    coordinates: [35.9990522, -78.9290629],
    address: "2001 Campus Drive",
    summary: "Duke ?????????????????????",
    facts: ["????????????", "? West Campus ??????"],
    source: {
      label: "Nasher Museum of Art",
      url: "https://nasher.duke.edu/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "NM",
    previewEmoji: "???",
  },
  {
    id: "american-tobacco",
    name: "American Tobacco Campus",
    shortName: "American Tobacco",
    category: "attraction",
    categoryLabel: "?? ? ??",
    area: "durham",
    coordinates: [35.9943285, -78.904297],
    summary: "?????????????????????? Durham ???",
    facts: ["?? DBAP ? DPAC", "??? Downtown Durham ????"],
    source: {
      label: "Discover Durham ? Things to Do",
      url: "https://www.discoverdurham.com/things-to-do/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "AT",
    previewEmoji: "???",
  },
  {
    id: "durham-bulls",
    name: "Durham Bulls Athletic Park",
    shortName: "Durham Bulls",
    category: "attraction",
    categoryLabel: "?? ? ??",
    area: "durham",
    coordinates: [35.9915839, -78.9039173],
    address: "409 Blackwell Street",
    summary: "Durham Bulls ????????? American Tobacco Campus ?????",
    facts: ["????????????", "?????????????"],
    source: {
      label: "Durham Bulls",
      url: "https://www.milb.com/durham",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "DB",
    previewEmoji: "?",
  },
  {
    id: "life-science-museum",
    name: "Museum of Life and Science",
    shortName: "Life + Science",
    category: "attraction",
    categoryLabel: "?????",
    area: "durham",
    coordinates: [36.031267, -78.8965307],
    summary: "????????????????????",
    facts: ["??????????", "????????????"],
    source: {
      label: "Discover Durham ? Things to Do",
      url: "https://www.discoverdurham.com/things-to-do/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "LS",
    previewEmoji: "??",
  },
  {
    id: "eno-river",
    name: "Eno River State Park",
    shortName: "Eno River",
    category: "attraction",
    categoryLabel: "???? ? ??",
    area: "durham",
    coordinates: [36.0749299, -79.0172182],
    summary: "Durham ??????????????",
    facts: ["??????????", "???????????????"],
    source: {
      label: "NC State Parks ? Eno River",
      url: "https://www.ncparks.gov/state-parks/eno-river-state-park",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "ER",
    previewEmoji: "??",
  },
  {
    id: "duke-lemur-center",
    name: "Duke Lemur Center",
    shortName: "Lemur Center",
    category: "attraction",
    categoryLabel: "???????",
    area: "durham",
    coordinates: [35.9941971, -78.9623365],
    summary: "Duke ??????????????????????",
    facts: ["????????????????", "???????????"],
    source: {
      label: "Duke Lemur Center",
      url: "https://lemur.duke.edu/visit/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "LC",
    previewEmoji: "??",
  },
  {
    id: "dpac",
    name: "Durham Performing Arts Center",
    shortName: "DPAC",
    category: "attraction",
    categoryLabel: "?? ? ??",
    area: "durham",
    coordinates: [35.9932676, -78.9022327],
    address: "123 Vivian Street",
    summary: "Durham ?????????????????????",
    facts: ["?? American Tobacco Campus", "????????????"],
    source: {
      label: "DPAC Official",
      url: "https://www.dpacnc.com/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "DP",
    previewEmoji: "???",
  },
  {
    id: "southpoint",
    name: "The Streets at Southpoint",
    shortName: "Southpoint",
    category: "shopping",
    categoryLabel: "?? ? ??",
    area: "durham",
    coordinates: [35.90419, -78.9437055],
    address: "6910 Fayetteville Road",
    summary: "Durham ???????????????????????",
    facts: ["??????????", "???????????"],
    source: {
      label: "Discover Durham ? Things to Do",
      url: "https://www.discoverdurham.com/things-to-do/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "SP",
    previewEmoji: "???",
  },
  {
    id: "downtown-durham",
    name: "Downtown Durham ? CCB Plaza",
    shortName: "Downtown Durham",
    category: "attraction",
    categoryLabel: "??? ? ??",
    area: "durham",
    coordinates: [35.99645, -78.9012],
    summary: "???? Downtown Durham ????????????????????????",
    facts: ["?? American Tobacco?DPAC?DBAP ??", "????????"],
    source: {
      label: "Discover Durham ? Things to Do",
      url: "https://www.discoverdurham.com/things-to-do/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "DT",
    previewEmoji: "??",
  },
  {
    id: "unc-old-well",
    name: "UNC Old Well",
    shortName: "UNC Old Well",
    category: "attraction",
    categoryLabel: "Chapel Hill ??",
    area: "triangle",
    coordinates: [35.91296, -79.05122],
    summary: "UNC Chapel Hill ??????????? Franklin Street ?????",
    facts: ["???????", "?????????"],
    source: {
      label: "UNC Chapel Hill ? The Old Well",
      url: "https://www.unc.edu/discover/the-old-well/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "UNC",
    previewEmoji: "???",
  },
  {
    id: "franklin-street",
    name: "Franklin Street",
    shortName: "Franklin Street",
    category: "attraction",
    categoryLabel: "Chapel Hill ????",
    area: "triangle",
    coordinates: [35.9137, -79.0555],
    summary: "UNC ????????????????????????",
    facts: ["??? UNC ????", "??????????"],
    source: {
      label: "Visit Chapel Hill",
      url: "https://www.visitchapelhill.org/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "FS",
    previewEmoji: "??",
  },
  {
    id: "nc-botanical-garden",
    name: "North Carolina Botanical Garden",
    shortName: "NC Botanical Garden",
    category: "attraction",
    categoryLabel: "??? ? ??",
    area: "triangle",
    coordinates: [35.8973342, -79.0311056],
    summary: "UNC ??????????????",
    facts: ["??????", "????????????????"],
    source: {
      label: "North Carolina Botanical Garden",
      url: "https://ncbg.unc.edu/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "BG",
    previewEmoji: "??",
  },
  {
    id: "ncma",
    name: "North Carolina Museum of Art",
    shortName: "NC Museum of Art",
    category: "attraction",
    categoryLabel: "??? ? ????",
    area: "triangle",
    coordinates: [35.8105029, -78.7021777],
    address: "2110 Blue Ridge Road, Raleigh",
    summary: "Raleigh ???????????????????????",
    facts: ["??????", "???????????????"],
    source: {
      label: "Visit Raleigh ? Museum Guide",
      url: "https://www.visitraleigh.com/things-to-do/museums/museum-guide/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "MA",
    previewEmoji: "??",
  },
  {
    id: "natural-sciences",
    name: "North Carolina Museum of Natural Sciences",
    shortName: "Natural Sciences",
    category: "attraction",
    categoryLabel: "???????",
    area: "triangle",
    coordinates: [35.7821583, -78.6395026],
    address: "11 West Jones Street, Raleigh",
    summary: "Raleigh ???????????????? State Capitol ?????",
    facts: ["?????????", "??????????"],
    source: {
      label: "Visit Raleigh ? Museum Guide",
      url: "https://www.visitraleigh.com/things-to-do/museums/museum-guide/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "NS",
    previewEmoji: "??",
  },
  {
    id: "dix-park",
    name: "Dorothea Dix Park",
    shortName: "Dix Park",
    category: "attraction",
    categoryLabel: "?? ? ????",
    area: "triangle",
    coordinates: [35.7700706, -78.6568071],
    summary: "Raleigh ??????????????????????",
    facts: ["?????????????", "?????????"],
    source: {
      label: "Visit Raleigh ? Things to Do",
      url: "https://www.visitraleigh.com/things-to-do/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "DX",
    previewEmoji: "??",
  },
  {
    id: "pullen-park",
    name: "Pullen Park",
    shortName: "Pullen Park",
    category: "attraction",
    categoryLabel: "?? ? ????",
    area: "triangle",
    coordinates: [35.7821253, -78.663551],
    summary: "?? NC State ?????????????????????",
    facts: ["????????", "????????"],
    source: {
      label: "Visit Raleigh ? Family Fun",
      url: "https://www.visitraleigh.com/things-to-do/family-fun/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "PP",
    previewEmoji: "??",
  },
  {
    id: "nc-state-capitol",
    name: "North Carolina State Capitol",
    shortName: "NC State Capitol",
    category: "attraction",
    categoryLabel: "?? ? ??",
    area: "triangle",
    coordinates: [35.7803975, -78.6390995],
    address: "1 East Edenton Street, Raleigh",
    summary: "Raleigh ?????????????????????????",
    facts: ["?????????", "???????????"],
    source: {
      label: "Visit Raleigh ? Raleigh Guide",
      url: "https://www.visitraleigh.com/plan-a-trip/cities-and-towns/raleigh/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "SC",
    previewEmoji: "???",
  },
  {
    id: "umstead-park",
    name: "William B. Umstead State Park",
    shortName: "Umstead Park",
    category: "attraction",
    categoryLabel: "???? ? ??",
    area: "triangle",
    coordinates: [35.8571605, -78.7544348],
    summary: "RDU ?????????????????????",
    facts: ["????????", "???????????????"],
    source: {
      label: "NC State Parks ? Umstead",
      url: "https://www.ncparks.gov/state-parks/william-b-umstead-state-park",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "UP",
    previewEmoji: "??",
  },
  {
    id: "downtown-cary-park",
    name: "Downtown Cary Park",
    shortName: "Downtown Cary Park",
    category: "attraction",
    categoryLabel: "?? ? ????",
    area: "triangle",
    coordinates: [35.7838447, -78.77988],
    address: "319 South Academy Street, Cary",
    summary: "Downtown Cary ??????????????????????",
    facts: ["?? Cary ???????", "????????????"],
    source: {
      label: "Downtown Cary Park",
      url: "https://downtowncarypark.com/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "CP",
    previewEmoji: "?",
  },
  {
    id: "chase-ninth-street",
    name: "Chase Bank ? Durham 9th Street",
    shortName: "Chase Bank",
    category: "service",
    categoryLabel: "?? ? ATM",
    area: "ninth",
    coordinates: [36.008513, -78.92223],
    address: "725 9th Street, Durham",
    summary: "Ninth Street ?? Chase ??????????????? ATM?",
    facts: ["??? ATM ????????", "???????????????"],
    source: {
      label: "Chase ? Durham 9th St",
      url: "https://locator.chase.com/nc/durham/725-9th-st",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "$",
    previewEmoji: "??",
  },
  {
    id: "regulator-bookshop",
    name: "The Regulator Bookshop",
    shortName: "Regulator Books",
    category: "shopping",
    categoryLabel: "????",
    area: "ninth",
    coordinates: [36.0085447, -78.9218424],
    address: "720 9th Street, Durham",
    summary: "Ninth Street ???????????????????????",
    facts: ["Triangle ?????????", "??????????????"],
    source: {
      label: "The Regulator Bookshop",
      url: "https://www.regulatorbookshop.com/about-us",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "BK",
    previewEmoji: "??",
  },
  {
    id: "hometown-apparel",
    name: "Hometown Apparel",
    shortName: "Hometown Apparel",
    category: "shopping",
    categoryLabel: "Durham ??? ? ??",
    area: "ninth",
    coordinates: [36.0090401, -78.9219945],
    address: "738 9th Street, Durham",
    summary: "?? Bull City ? Durham ????????????????????",
    facts: ["??? Durham ???", "? Discover Durham ??????"],
    source: {
      label: "Discover Durham ? Hometown Apparel",
      url: "https://www.discoverdurham.com/directory/hometown-apparel/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "HT",
    previewEmoji: "??",
  },
  {
    id: "durham-cycles",
    name: "Durham Cycles",
    shortName: "Durham Cycles",
    category: "service",
    categoryLabel: "???? ? ??",
    area: "ninth",
    coordinates: [36.009631, -78.9218154],
    address: "756 9th Street, Durham",
    summary: "Ninth Street ??????????????????????????",
    facts: ["???????????", "????????????"],
    source: {
      label: "Discover Durham ? Durham Cycles",
      url: "https://www.discoverdurham.com/directory/durham-cycles/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "DC",
    previewEmoji: "??",
  },
  {
    id: "barnes-supply",
    name: "Barnes Supply Co.",
    shortName: "Barnes Supply",
    category: "shopping",
    categoryLabel: "???????",
    area: "ninth",
    coordinates: [36.010293, -78.9217344],
    address: "774 9th Street, Durham",
    summary: "Ninth Street ??????????????",
    facts: ["??????????????", "??????????????"],
    source: {
      label: "Discover Durham ? Barnes Supply",
      url: "https://www.discoverdurham.com/directory/barnes-supply-co/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "BS",
    previewEmoji: "??",
  },
  {
    id: "red-mango-wilson",
    name: "Red Mango ? Wilson Recreation Center",
    shortName: "Red Mango",
    category: "food",
    categoryLabel: "???? ? ?????",
    area: "west",
    coordinates: [35.9969018, -78.9406545],
    address: "Wilson Recreation Center, 330 Towerview Road",
    summary: "Wilson Recreation Center ?? Red Mango????????????????",
    facts: ["?? Wilson Recreation Center", "????? Duke Campus Hours ??????"],
    source: {
      label: "Duke Campus Hours ? Dining",
      url: "https://campushours.oit.duke.edu/places/dining",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "RM",
    previewEmoji: "??",
  },
  {
    id: "saladelia-perkins",
    name: "Saladelia @ The Perk",
    shortName: "Saladelia Perkins",
    category: "food",
    categoryLabel: "???? ? ?????",
    area: "west",
    coordinates: [36.003204, -78.938078],
    address: "Von der Heyden Pavilion, Perkins Library",
    summary: "Perkins / Bostock ?????????????????????????????",
    facts: ["?????????????????", "???????????????"],
    source: {
      label: "Duke Libraries ? Amenities",
      url: "https://library.duke.edu/using/amenities",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "SD",
    previewEmoji: "??",
  },
  {
    id: "mcdonalds-bryan",
    name: "McDonald's ? Bryan Center",
    shortName: "McDonald's Bryan",
    category: "food",
    categoryLabel: "???? ? ??",
    area: "west",
    coordinates: [36.001109, -78.941488],
    address: "Bryan Center, 125 Science Drive",
    summary: "Bryan Center ?????????????????",
    facts: ["?? Bryan Center", "????? Duke Campus Hours ??????"],
    source: {
      label: "Duke Campus Hours ? Dining",
      url: "https://campushours.oit.duke.edu/places/dining",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "M",
    previewEmoji: "??",
  },
  {
    id: "trinity-cafe",
    name: "Trinity Cafe",
    shortName: "Trinity Cafe",
    category: "food",
    categoryLabel: "???? ? East ??",
    area: "east",
    coordinates: [36.0075937, -78.9139503],
    address: "East Campus Union, 1324 Campus Drive",
    summary: "East Campus Union ?????????????????????",
    facts: ["? Marketplace ??", "????? Duke Campus Hours ??????"],
    source: {
      label: "Duke Campus Hours ? Dining",
      url: "https://campushours.oit.duke.edu/places/dining",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "TC",
    previewEmoji: "?",
  },
  {
    id: "nan-xiang-express",
    name: "Nan Xiang Express & Tsaocha",
    shortName: "Nan Xiang Express",
    category: "food",
    categoryLabel: "Duke ???? ? ??????",
    area: "essentials",
    coordinates: [36.005522, -78.9226205],
    address: "1605 Erwin Road, Durham",
    summary: "Blue Light Living ??????????????? CSF ? Blue Light ????",
    facts: ["??????????????", "Blue Light Shuttle ?????"],
    source: {
      label: "Discover Durham ? Nan Xiang Express",
      url: "https://www.discoverdurham.com/directory/nan-xiang-express/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "NX",
    previewEmoji: "??",
  },
  {
    id: "sushi-love",
    name: "Sushi Love",
    shortName: "Sushi Love",
    category: "food",
    categoryLabel: "Duke ???? ? ??",
    area: "essentials",
    coordinates: [36.0070336, -78.9472546],
    address: "2812 Erwin Road, Suite 204, Durham",
    summary: "Erwin Road ??? Duke ?????????????",
    facts: ["????????????", "? West Campus ????????"],
    source: {
      label: "Discover Durham ? Sushi Love",
      url: "https://www.discoverdurham.com/directory/sushi-love/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "SL",
    previewEmoji: "??",
  },
  {
    id: "naanstop-erwin",
    name: "NaanStop Indian Cuisine",
    shortName: "NaanStop",
    category: "food",
    categoryLabel: "Duke ???? ? ???",
    area: "essentials",
    coordinates: [36.006925, -78.94716],
    address: "2812 Erwin Road, Durham",
    summary: "Erwin Road ?????????????????????",
    facts: ["?????????????", "? West Campus ????????"],
    source: {
      label: "Discover Durham ? NaanStop",
      url: "https://www.discoverdurham.com/directory/naanstop-indian-cuisine/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "NN",
    previewEmoji: "??",
  },
  {
    id: "enzos-pizza",
    name: "Enzo's Pizza Co.",
    shortName: "Enzo's Pizza",
    category: "food",
    categoryLabel: "Duke ???? ? ??",
    area: "essentials",
    coordinates: [36.0091759, -78.9444179],
    address: "2608 Erwin Road, Durham",
    summary: "Erwin Road ??? Duke ????????????????????",
    facts: ["??????????", "? West Campus ????????"],
    source: {
      label: "Discover Durham ? Enzo's Pizza",
      url: "https://www.discoverdurham.com/directory/enzos-pizza-co/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "EZ",
    previewEmoji: "??",
  },
];

const SHUTTLE_SOURCE_URL =
  "https://duke.transloc.com/routes/23/stops";

export const PLACES: Place[] = [
  ...BASE_PLACES,
  ...SHUTTLE_STOPS.filter(
    (stop) =>
      stop.id !== "east-campus-statue-stop" &&
      stop.id !== "swift-300-shuttle-stop",
  ).map(
    (stop): Place => ({
      id: stop.id,
      name: `${stop.name} ? Shuttle Stop`,
      shortName: stop.shortName,
      category: "transit",
      categoryLabel: "Shuttle ?? ? CSF",
      area: stop.area,
      coordinates: stop.coordinates,
      summary: `${SHUTTLE_ROUTE_NAME} ?????????? Duke ?? GTFS?`,
      facts: [
        stop.stopCode ? `?????${stop.stopCode}` : "????? TransLoc ??",
        "?? Shuttle ???????????????????",
      ],
      source: {
        label: "Duke Transit GTFS + TransLoc",
        url: SHUTTLE_SOURCE_URL,
        checkedAt: "2026-07-23",
      },
      confidence: "verified",
      markerLabel: "S",
      previewEmoji: "??",
      shuttle: {
        route: SHUTTLE_ROUTE_NAME,
        summary: "????????????????? TransLoc?",
        liveUrl: "https://duke.transloc.com/",
      },
    }),
  ),
];

export const FALL_2026_PLAN = [
  {
    day: "?? / ??",
    items: [
      { time: "10:05", course: "GLHLTH 101", placeId: "social-sciences" },
      { time: "11:45", course: "KOREAN 101 ? ??", placeId: "languages" },
    ],
  },
  {
    day: "?? / ??",
    items: [
      { time: "08:30", course: "FIN ACCOUNTING 174", placeId: "french-science" },
      { time: "???", course: "MATH 333 / 431", placeId: "physics" },
    ],
  },
];

export const OFFICIAL_LINKS = [
  { label: "Duke ??????", url: "https://maps.duke.edu/" },
  {
    label: "Duke Transit ?????",
    url: "https://parking.duke.edu/buses-vans/",
  },
  { label: "TransLoc ????", url: "https://duke.transloc.com/" },
  { label: "GoTriangle ????", url: "https://gotriangle.org/" },
  { label: "RDU ??????", url: "https://www.rdu.com/ground-transportation/" },
  {
    label: "Duke Dining ????",
    url: "https://students.duke.edu/living/dining/dining-locations/",
  },
  { label: "Discover Durham", url: "https://www.discoverdurham.com/" },
  { label: "Visit Raleigh", url: "https://www.visitraleigh.com/" },
  { label: "Duke ePrint ??", url: "https://eprint.oit.duke.edu/" },
];
